package Ventanas.SubVentanas;

import Clases.ArchivoClientes;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class AddClientes extends javax.swing.JInternalFrame {
private ArchivoClientes ACInstance;
    /**
     * Creates new form AddClientes
     */
    public AddClientes() {
        initComponents();
        setLocation(230, 0);
        ACInstance = new ArchivoClientes();
        
        PetAge.removeAllItems();
        for(int i = 1; i<=20;i++){
            PetAge.addItem("" + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CliName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CliNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CliEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetDetails1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        PetDetails2 = new javax.swing.JTextArea();
        PetName = new javax.swing.JTextField();
        PetType = new javax.swing.JComboBox<>();
        PetSubType = new javax.swing.JTextField();
        PetCol = new javax.swing.JTextField();
        AddCliBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PetAge = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        PetGen = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(185, 209, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(140, 172, 197));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 62, 92));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir clientes");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 553, -1));

        jLabel2.setBackground(new java.awt.Color(233, 242, 249));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datos de la mascota");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, 553, 23));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, -1));

        CliName.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        CliName.setBorder(null);
        jPanel1.add(CliName, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 69, 166, 25));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Número de telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 76, -1, -1));

        CliNum.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        CliNum.setBorder(null);
        jPanel1.add(CliNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 69, 161, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Correo electronico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));

        CliEmail.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        CliEmail.setBorder(null);
        jPanel1.add(CliEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 106, 201, 25));

        jSeparator1.setBackground(new java.awt.Color(84, 122, 168));
        jSeparator1.setForeground(new java.awt.Color(84, 122, 168));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 143, 6, 10));

        jLabel6.setBackground(new java.awt.Color(233, 242, 249));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Datos del cliente");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 553, 23));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Especie");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 186, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Raza");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 224, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 224, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Condiciones medicas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Edad");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Notas adicionales");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        PetDetails1.setColumns(20);
        PetDetails1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetDetails1.setLineWrap(true);
        PetDetails1.setRows(5);
        PetDetails1.setBorder(null);
        jScrollPane1.setViewportView(PetDetails1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 419, 55));

        PetDetails2.setColumns(20);
        PetDetails2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetDetails2.setLineWrap(true);
        PetDetails2.setRows(5);
        PetDetails2.setBorder(null);
        jScrollPane2.setViewportView(PetDetails2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 419, 55));

        PetName.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetName.setBorder(null);
        jPanel1.add(PetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 156, 25));

        PetType.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar especie", "Perro", "Gato", "Ave", "Roedor" }));
        PetType.setBorder(null);
        PetType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetTypeActionPerformed(evt);
            }
        });
        jPanel1.add(PetType, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 178, 150, -1));

        PetSubType.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetSubType.setBorder(null);
        jPanel1.add(PetSubType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 156, 25));

        PetCol.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetCol.setBorder(null);
        jPanel1.add(PetCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 217, 168, 25));

        AddCliBtn.setBackground(new java.awt.Color(199, 249, 241));
        AddCliBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AddCliBtn.setText("Añadir");
        AddCliBtn.setBorder(null);
        AddCliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddCliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCliBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddCliBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 128, 37));

        jButton2.setBackground(new java.awt.Color(250, 152, 196));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Salir");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 75, 38));

        PetAge.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(PetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Sexo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        PetGen.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        PetGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Macho", "Hembra" }));
        PetGen.setBorder(null);
        jPanel1.add(PetGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PetTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetTypeActionPerformed

    private void AddCliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCliBtnActionPerformed
        JOptionPane.showMessageDialog(null, ACInstance.GuardarDatos(CliName.getText(), CliNum.getText(), CliEmail.getText(),
                        PetName.getText(), PetGen.getSelectedItem().toString(), PetType.getSelectedItem().toString(),
                        PetSubType.getText(), PetCol.getText(), PetAge.getSelectedItem().toString(), PetDetails1.getText(), PetDetails2.getText()));
    }//GEN-LAST:event_AddCliBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCliBtn;
    private javax.swing.JTextField CliEmail;
    private javax.swing.JTextField CliName;
    private javax.swing.JTextField CliNum;
    private javax.swing.JComboBox<String> PetAge;
    private javax.swing.JTextField PetCol;
    private javax.swing.JTextArea PetDetails1;
    private javax.swing.JTextArea PetDetails2;
    private javax.swing.JComboBox<String> PetGen;
    private javax.swing.JTextField PetName;
    private javax.swing.JTextField PetSubType;
    private javax.swing.JComboBox<String> PetType;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
