package Ventanas.SubVentanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;
import javax.swing.JOptionPane;

public class CitasAdd extends javax.swing.JInternalFrame {

    public CitasAdd() {
        initComponents();
        setLocation(115,0);
        cargarClientes();
        
        NomClient.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CargarMascotas();
            }
        });
        CargarMascotas();
    }
                
    public void cargarClientes() {
        Set<String> nombresClientesUnicos = new HashSet<>(); 
        String nombreArchivo = "Clientes.txt"; // Ruta a tu archivo de clientes

        try (BufferedReader reader = new BufferedReader(new FileReader(nombreArchivo))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                // Divide la línea usando el punto y coma como delimitador
                String[] partes = linea.split(";");

                // Asegúrate de que la línea tenga al menos el primer campo
                if (partes.length > 0) { 
                    String nombreCliente = partes[0].trim();
                    nombresClientesUnicos.add(nombreCliente); // HashSet añade solo si no existe
                }
            }
        } catch (Exception e) {
            System.out.println("Error");
        }

        // Limpiar el combobox de clientes antes de añadir los nuevos ítems
        NomClient.removeAllItems(); 
        // Añadir cada nombre único al combobox de clientes
        NomClient.addItem("Seleccionar Cliente");
        for (String nombre : nombresClientesUnicos) {
            NomClient.addItem(nombre);
        }
    }
    
    public void CargarMascotas() {
        String clienteSeleccionado = (String) NomClient.getSelectedItem();
        
        // Si no hay cliente seleccionado, limpiar el combobox de mascotas y salir
        if (clienteSeleccionado == null) {
            PetOp.removeAllItems();
            return;
        }

        // LinkedList para almacenar las mascotas del cliente seleccionado
        LinkedList<String> mascotasDelCliente = new LinkedList<>();
        String nombreArchivo = "Clientes.txt"; // Ruta a tu archivo de clientes

        try (BufferedReader reader = new BufferedReader(new FileReader(nombreArchivo))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                // Divide la línea usando el punto y coma. Usar -1 para mantener campos vacíos al final.
                String[] partes = linea.split(";", -1); 

                // Verificar que la línea tenga al menos el nombre del cliente y el nombre de la mascota
                if (partes.length > 3) { // Necesitamos al menos 4 partes (índices 0 a 3)
                    String nombreClienteLinea = partes[0].trim();
                    String nombreMascotaLinea = partes[3].trim();

                    // Si el nombre del cliente en la línea coincide con el seleccionado
                    if (nombreClienteLinea.equals(clienteSeleccionado)) {
                        mascotasDelCliente.add(nombreMascotaLinea);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error");
        }

        // Limpiar y rellenar el combobox de mascotas con los resultados filtrados
        PetOp.removeAllItems();
        PetOp.addItem("Seleccionar mascota");
        for (String mascota : mascotasDelCliente) {
            PetOp.addItem(mascota);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomClient = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MotivoBox = new javax.swing.JComboBox<>();
        FechaCita = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        HoraCita = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PayMethod = new javax.swing.JComboBox<>();
        GuardarCita = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observaciones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        PetOp = new javax.swing.JComboBox<>();

        setTitle("Añadir Citas");

        jPanel1.setBackground(new java.awt.Color(232, 241, 242));

        ExitBtn.setBackground(new java.awt.Color(250, 152, 196));
        ExitBtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBtn.setText("Salir");
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.setOpaque(true);
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del Cliente");

        NomClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Motivo");

        MotivoBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MotivoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el motivo ", "Vacuna", "Revisión", "Esterilización", "Parto", "Emergencia" }));

        FechaCita.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Hora");

        HoraCita.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Modo de Pago ");

        PayMethod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));
        PayMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayMethodActionPerformed(evt);
            }
        });

        GuardarCita.setText("Guardar Cita");
        GuardarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCitaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Observaciones");

        Observaciones.setColumns(20);
        Observaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Observaciones.setLineWrap(true);
        Observaciones.setRows(5);
        jScrollPane1.setViewportView(Observaciones);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Mascota");

        PetOp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MotivoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NomClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PetOp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(FechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(HoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212)
                                .addComponent(GuardarCita))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(NomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(PetOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotivoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HoraCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(FechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarCita)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void PayMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayMethodActionPerformed

    private void GuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCitaActionPerformed
        
    }//GEN-LAST:event_GuardarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBtn;
    private com.toedter.calendar.JCalendar FechaCita;
    private javax.swing.JButton GuardarCita;
    private javax.swing.JComboBox<String> HoraCita;
    private javax.swing.JComboBox<String> MotivoBox;
    private javax.swing.JComboBox<String> NomClient;
    private javax.swing.JTextArea Observaciones;
    private javax.swing.JComboBox<String> PayMethod;
    private javax.swing.JComboBox<String> PetOp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
