/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Ventanas.MenuDoctor;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Credbutton = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        Ingresarbtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(79, 125, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bannerLogin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 77, 290, 260));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 87, 126));
        jLabel2.setText("Citas para veterinaria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Credbutton.setBackground(new java.awt.Color(235, 245, 238));
        Credbutton.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Credbutton.setForeground(new java.awt.Color(102, 165, 173));
        Credbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/infoicon.png"))); // NOI18N
        Credbutton.setText("Usuarios");
        Credbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Credbutton.setOpaque(true);
        Credbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CredbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(Credbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/BG1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(232, 232, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1000946(1).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 165, 173));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio de sesión");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        User.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        User.setBorder(null);
        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 165, 173));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 165, 173));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        Pass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Pass.setBorder(null);
        jPanel2.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 30));

        Ingresarbtn.setBackground(new java.awt.Color(102, 165, 173));
        Ingresarbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ingresarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Ingresarbtn.setText("Ingresar");
        Ingresarbtn.setBorder(null);
        Ingresarbtn.setBorderPainted(false);
        Ingresarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresarbtn.setFocusPainted(false);
        Ingresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Ingresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 30));

        ExitBtn.setBackground(new java.awt.Color(250, 152, 196));
        ExitBtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBtn.setText("X");
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.setOpaque(true);
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });
        jPanel2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 30, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void IngresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarbtnActionPerformed
            if(User.getText().equals("Doctor") && Pass.getText().equals("pass1")){
                MenuDoctor MD = new MenuDoctor();
                MD.setVisible(true);
                MD.setLocationRelativeTo(null);
                dispose();
                JOptionPane.showMessageDialog(null, "¡Bienvenido Doctor!", "Bienvenido", JOptionPane.PLAIN_MESSAGE);
            }
            else if(User.getText().equals("AuxCitas1") && Pass.getText().equals("pass2")){
                MenuAuxiliar MA = new MenuAuxiliar();
                MA.setVisible(true);
                MA.setLocationRelativeTo(null);
                dispose();
                JOptionPane.showMessageDialog(null, "¡Bienvenido Auxiliar!", "Bienvenido", JOptionPane.PLAIN_MESSAGE);
            }
            else if(User.getText().equals("Admin") && Pass.getText().equals("root")){
                MenuAdmin MAd = new MenuAdmin();
                MAd.setVisible(true);
                MAd.setLocationRelativeTo(null);
                dispose();
                JOptionPane.showMessageDialog(null, "¡Bienvenido Administrador!", "Modo Administrador", JOptionPane.PLAIN_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Datos ingresados erroneos\nVerificar Usuario y/o Contraseña", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_IngresarbtnActionPerformed

    private void CredbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CredbuttonMouseClicked
        JOptionPane.showMessageDialog(null, "1. AuxCitas1 | pass2 \n"
                                        + "2. Doctor | pass1\n"
                                        + "3. Admin | root",
                                        "Credenciales de acceso", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_CredbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Credbutton;
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JButton Ingresarbtn;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
